parameters:
  buildConfiguration: 'Release'

steps:

#Compila proyecto
- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{ parameters.buildConfiguration }} '
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }} '
    projects: '**/*.csproj'

# Publica zipeado del proyecto
- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.builsConfioguration }} '
  inputs:
    command: 'publish'    
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'